CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT chk_app_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    profile_image_content_type VARCHAR(255),
    profile_image_content BYTEA
);

CREATE TABLE IF NOT EXISTS schedule_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    color VARCHAR(255) NOT NULL,
    level VARCHAR(255) NOT NULL,
    teacher_id BIGINT NOT NULL,
    CONSTRAINT fk_schedule_entries_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id)
);

CREATE INDEX IF NOT EXISTS idx_schedule_entries_teacher_id ON schedule_entries (teacher_id);
CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users (username);
