CREATE TABLE IF NOT EXISTS yoga_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    image_content_type VARCHAR(255),
    image_content BYTEA
);

ALTER TABLE schedule_entries
    ADD COLUMN IF NOT EXISTS yoga_class_id BIGINT;

UPDATE schedule_entries
SET yoga_class_id = (
    SELECT id
    FROM yoga_classes
    WHERE name = 'Allgemein'
    ORDER BY id
    LIMIT 1
)
WHERE yoga_class_id IS NULL;

ALTER TABLE schedule_entries
    ALTER COLUMN yoga_class_id SET NOT NULL;

ALTER TABLE schedule_entries
    DROP COLUMN IF EXISTS color;

DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_schedule_entries_yoga_class'
    ) THEN
        ALTER TABLE schedule_entries
            ADD CONSTRAINT fk_schedule_entries_yoga_class
                FOREIGN KEY (yoga_class_id) REFERENCES yoga_classes (id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_schedule_entries_yoga_class_id ON schedule_entries (yoga_class_id);
